## 一.构造分类器

In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('data/bankdebt.csv', index_col=0, header=None)
data

1         2     3    4
0                           
1   Yes    Single  12.5   No
2    No   Married  10.0   No
3    No    Single   7.0   No
4   Yes   Married  12.0   No
5    No  Divorced   9.5  Yes
6    No   Married   6.0   No
7   Yes  Divorced  22.0   No
8    No    Single   8.5  Yes
9    No   Married   7.5   No
10   No    Single   9.0  Yes
11   No    Single   5.5  Yes
12  Yes   Married   8.0   No
13  Yes  Divorced  11.0   No
14   No    Single   9.5   No
15   No  Divorced   6.7  Yes

In [2]:
data.loc[data[1]=='Yes',1]=1
data.loc[data[1]=='No',1]=0
data.loc[data[4]=='Yes',4]=1
data.loc[data[4]=='No',4]=0
data.loc[data[2]=='Single',2]=1
data.loc[data[2]=='Married',2]=2
data.loc[data[2]=='Divorced',2]=3
data

1  2     3  4
0                
1   1  1  12.5  0
2   0  2  10.0  0
3   0  1   7.0  0
4   1  2  12.0  0
5   0  3   9.5  1
6   0  2   6.0  0
7   1  3  22.0  0
8   0  1   8.5  1
9   0  2   7.5  0
10  0  1   9.0  1
11  0  1   5.5  1
12  1  2   8.0  0
13  1  3  11.0  0
14  0  1   9.5  0
15  0  3   6.7  1

In [3]:
x = data.iloc[:,0:3].values.astype(float)  # 取出前3列数据，是特征属性值
x

array([[ 1. ,  1. , 12.5],
       [ 0. ,  2. , 10. ],
       [ 0. ,  1. ,  7. ],
       [ 1. ,  2. , 12. ],
       [ 0. ,  3. ,  9.5],
       [ 0. ,  2. ,  6. ],
       [ 1. ,  3. , 22. ],
       [ 0. ,  1. ,  8.5],
       [ 0. ,  2. ,  7.5],
       [ 0. ,  1. ,  9. ],
       [ 0. ,  1. ,  5.5],
       [ 1. ,  2. ,  8. ],
       [ 1. ,  3. , 11. ],
       [ 0. ,  1. ,  9.5],
       [ 0. ,  3. ,  6.7]])

In [4]:
y = data[4].values.astype(int)   # 最后1列数据是分类标签,取出赋给变量y
y

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1])

In [5]:
from sklearn import tree    # 导入决策树模块，训练分类器
clf = tree.DecisionTreeClassifier()   # 模型初始化
clf = clf.fit(x,y)    # 模型学习

## 二.对分类器的性能进行评估

In [6]:
print('模型预测的准确率：')
print(clf.score(x,y))

模型预测的准确率：
1.0


In [7]:
predicted_y = clf.predict(x)  # 使用创建的分类器对样本的分类进行预测
predicted_y

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1])

In [8]:
from sklearn import metrics
print('分类器的性能报告：')
print(metrics.classification_report(y, predicted_y))

分类器的性能报告：
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         5

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15



In [9]:
print('Confusion matrix:')
print(metrics.confusion_matrix(y, predicted_y))  # 分类器的混淆矩阵

Confusion matrix:
[[10  0]
 [ 0  5]]
