In [1]:
# 教材P21-26
import numpy as np
scores=np.array([[70,85,77,90,82,84,89],
                 [60,64,80,75,80,92,90],
                 [90,93,88,87,86,90,91],
                 [80,82,91,88,83,86,80],
                 [88,72,78,90,91,73,80]])
names=np.array(['王微','肖良英','方绮雯','刘旭阳','钱易铭'])
subjects=np.array(['Math','English','Python','Chinese','Art','Database','Physics'])

## 2.2.1基本算术运算 

### 1.二维数组与标量运算

In [2]:
scores+5

array([[75, 90, 82, 95, 87, 89, 94],
       [65, 69, 85, 80, 85, 97, 95],
       [95, 98, 93, 92, 91, 95, 96],
       [85, 87, 96, 93, 88, 91, 85],
       [93, 77, 83, 95, 96, 78, 85]])

In [3]:
a=np.ones((5,7)) * 5
a

array([[5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.]])

In [4]:
scores + a

array([[75., 90., 82., 95., 87., 89., 94.],
       [65., 69., 85., 80., 85., 97., 95.],
       [95., 98., 93., 92., 91., 95., 96.],
       [85., 87., 96., 93., 88., 91., 85.],
       [93., 77., 83., 95., 96., 78., 85.]])

### 2.二维数组与一维数组运算

In [5]:
bonus = np.array([3,4,5,3,6,7,2])
scores + bonus

array([[73, 89, 82, 93, 88, 91, 91],
       [63, 68, 85, 78, 86, 99, 92],
       [93, 97, 93, 90, 92, 97, 93],
       [83, 86, 96, 91, 89, 93, 82],
       [91, 76, 83, 93, 97, 80, 82]])

### 3.选定元素运算 

In [6]:
scores[names == '肖良英', subjects == 'English']

array([64])

In [7]:
scores[names == '肖良英', subjects == 'English'] + 5

array([69])

## 2.2.2 函数和矩阵运算
### 1.通用函数

In [8]:
np.floor(scores / 10)

array([[7., 8., 7., 9., 8., 8., 8.],
       [6., 6., 8., 7., 8., 9., 9.],
       [9., 9., 8., 8., 8., 9., 9.],
       [8., 8., 9., 8., 8., 8., 8.],
       [8., 7., 7., 9., 9., 7., 8.]])

In [9]:
np.subtract(scores, 3)

array([[67, 82, 74, 87, 79, 81, 86],
       [57, 61, 77, 72, 77, 89, 87],
       [87, 90, 85, 84, 83, 87, 88],
       [77, 79, 88, 85, 80, 83, 77],
       [85, 69, 75, 87, 88, 70, 77]])

### 2.聚集函数

In [10]:
scores.sum(axis = 0)

array([388, 396, 414, 430, 422, 425, 430])

In [11]:
scores[names == '王微'].mean(axis=-1)

array([82.42857143])

In [12]:
names[ scores[:,subjects == 'English'].argmax() ]

'方绮雯'

## 2.2.3 随机数组生成函数

In [13]:
np.random.randint(0,6,10)

array([5, 0, 4, 0, 2, 0, 0, 1, 2, 0])

In [14]:
np.random.randint(0, 2, size=(5,6))

array([[1, 0, 0, 0, 1, 1],
       [0, 0, 1, 1, 1, 1],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 1, 1],
       [0, 0, 1, 1, 0, 0]])

In [15]:
np.random.normal(0, 1, size=(4,5))

array([[ 0.78498694,  0.33594887, -2.18867714,  0.94077265, -0.51933186],
       [-2.2709055 , -0.63402186,  0.11965069, -0.08530738, -0.70153998],
       [ 0.42883162, -0.62678654, -1.86273558, -1.1138141 ,  0.8847862 ],
       [-1.04638639, -0.21174857,  0.03758055,  0.26988904,  0.49248974]])