###  创建二维数组 scores
###  创建二维数组  t

In [1]:
import numpy as np
scores=np.array([[70,85,77,90,82,84,89],
                 [60,64,80,75,80,92,90],
                 [90,93,88,87,86,90,91],
                 [80,82,91,88,83,86,80],
                 [88,72,78,90,91,73,80]])

In [2]:
scores

array([[70, 85, 77, 90, 82, 84, 89],
       [60, 64, 80, 75, 80, 92, 90],
       [90, 93, 88, 87, 86, 90, 91],
       [80, 82, 91, 88, 83, 86, 80],
       [88, 72, 78, 90, 91, 73, 80]])

In [3]:
t=np.arange(1,36).reshape(5,7)
t

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35]])

##  一、       数组算术运算

### 1. 将scores所有元素加10

In [4]:
scores+10

array([[ 80,  95,  87, 100,  92,  94,  99],
       [ 70,  74,  90,  85,  90, 102, 100],
       [100, 103,  98,  97,  96, 100, 101],
       [ 90,  92, 101,  98,  93,  96,  90],
       [ 98,  82,  88, 100, 101,  83,  90]])

### 2.  scores中所有元素乘以5


In [5]:
scores*5

array([[350, 425, 385, 450, 410, 420, 445],
       [300, 320, 400, 375, 400, 460, 450],
       [450, 465, 440, 435, 430, 450, 455],
       [400, 410, 455, 440, 415, 430, 400],
       [440, 360, 390, 450, 455, 365, 400]])

### 3. scores中所有元素除以10

In [6]:
scores/10

array([[7. , 8.5, 7.7, 9. , 8.2, 8.4, 8.9],
       [6. , 6.4, 8. , 7.5, 8. , 9.2, 9. ],
       [9. , 9.3, 8.8, 8.7, 8.6, 9. , 9.1],
       [8. , 8.2, 9.1, 8.8, 8.3, 8.6, 8. ],
       [8.8, 7.2, 7.8, 9. , 9.1, 7.3, 8. ]])

### 4. 两个数组相加   scores+t

In [7]:
scores+t

array([[ 71,  87,  80,  94,  87,  90,  96],
       [ 68,  73,  90,  86,  92, 105, 104],
       [105, 109, 105, 105, 105, 110, 112],
       [102, 105, 115, 113, 109, 113, 108],
       [117, 102, 109, 122, 124, 107, 115]])

###   5. 将scores数组中的第1列数乘以0.3 + 第2列数乘以0.7

In [8]:
scores[:,1]*0.3+scores[:,2]*0.7

array([79.4, 75.2, 89.5, 88.3, 76.2])

##  二、 通用函数

### 6.  计算数组scores中，各元素的平方根

In [9]:
np.sqrt(scores)

array([[8.36660027, 9.21954446, 8.77496439, 9.48683298, 9.05538514,
        9.16515139, 9.43398113],
       [7.74596669, 8.        , 8.94427191, 8.66025404, 8.94427191,
        9.59166305, 9.48683298],
       [9.48683298, 9.64365076, 9.38083152, 9.32737905, 9.2736185 ,
        9.48683298, 9.53939201],
       [8.94427191, 9.05538514, 9.53939201, 9.38083152, 9.11043358,
        9.2736185 , 8.94427191],
       [9.38083152, 8.48528137, 8.83176087, 9.48683298, 9.53939201,
        8.54400375, 8.94427191]])

###  7. 计算数组scores中，各元素的平方

In [10]:
np.square(scores)

array([[4900, 7225, 5929, 8100, 6724, 7056, 7921],
       [3600, 4096, 6400, 5625, 6400, 8464, 8100],
       [8100, 8649, 7744, 7569, 7396, 8100, 8281],
       [6400, 6724, 8281, 7744, 6889, 7396, 6400],
       [7744, 5184, 6084, 8100, 8281, 5329, 6400]])

## 三、聚集函数

In [11]:
scores

array([[70, 85, 77, 90, 82, 84, 89],
       [60, 64, 80, 75, 80, 92, 90],
       [90, 93, 88, 87, 86, 90, 91],
       [80, 82, 91, 88, 83, 86, 80],
       [88, 72, 78, 90, 91, 73, 80]])

### (1) 计算scores中，所有数中的最高分

In [12]:
scores.max()

93

### (2) 计算scores中，每一行的总分

In [13]:
scores.sum(axis = 1)

array([577, 541, 625, 590, 572])

### (3) 计算scores中，每一列的平均分，最高分，最低分

In [14]:
scores.mean(axis = 0)

array([77.6, 79.2, 82.8, 86. , 84.4, 85. , 86. ])

In [15]:
scores.max(axis = 0)

array([90, 93, 91, 90, 91, 92, 91])

In [16]:
scores.min(axis = 0)

array([60, 64, 77, 75, 80, 73, 80])

### (4) 计算scores中，每一列的最小值的索引

In [17]:
scores.argmin(axis = 0)

array([1, 1, 0, 1, 1, 4, 3])