### 2.1.1 一维数组对象

In [1]:
import numpy as np
names = np.array(['王微', '肖良英', '方绮雯', '刘旭阳', '钱易铭'])
names

array(['王微', '肖良英', '方绮雯', '刘旭阳', '钱易铭'], dtype='<U3')

In [2]:
subjects = np.array(['Math', 'English', 'Python', 'Chinese', 'Art', 'Database', 'Physics'])
subjects

array(['Math', 'English', 'Python', 'Chinese', 'Art', 'Database',
       'Physics'], dtype='<U8')

In [3]:
names.ndim

1

In [4]:
names.size

5

In [5]:
names.dtype

dtype('<U3')

In [6]:
names[2]

'方绮雯'

In [7]:
subjects[-3]

'Art'

In [8]:
subjects[ [0,2,4] ]

array(['Math', 'Python', 'Art'], dtype='<U8')

In [9]:
names[ 1:4 ]

array(['肖良英', '方绮雯', '刘旭阳'], dtype='<U3')

In [10]:
subjects[ :-1:2]

array(['Math', 'Python', 'Art'], dtype='<U8')

In [11]:
names [ (names == '王微') | (names == '钱易铭') ]

array(['王微', '钱易铭'], dtype='<U3')

In [12]:
mask = (names == '王微') | (names == '钱易铭') 
mask

array([ True, False, False, False,  True])

### 2.1.2 二维数组对象

In [13]:
import numpy as np
scores = np.array([[70, 85, 77, 90, 82, 84, 89],
[60, 64, 80, 75, 80, 92, 90],
[90, 93, 88, 87, 86, 90, 91],
[80, 82, 91, 88, 83, 86, 80],
[88, 72, 78, 90, 91, 73, 80]])
scores

array([[70, 85, 77, 90, 82, 84, 89],
       [60, 64, 80, 75, 80, 92, 90],
       [90, 93, 88, 87, 86, 90, 91],
       [80, 82, 91, 88, 83, 86, 80],
       [88, 72, 78, 90, 91, 73, 80]])

In [14]:
# 查看数组属性
print("数组维数:",scores.ndim)
print("数组元素总数=行数×列数:",scores.size)
print("数组的行数和列数:",scores.shape)
print("数组元素的类型:",scores.dtype)

数组维数: 2
数组元素总数=行数×列数: 35
数组的行数和列数: (5, 7)
数组元素的类型: int64


In [15]:
# 二维数组切片基本格式 arr[row, col] 如果行或列用":"代替，表示选中对应的所有行或列
# 访问指定行、列元素
print(scores[1,0])
print(scores[[1,3],[0,1]])

60
[60 82]


In [16]:
# 访问部分行元素，给出行列表即可，列索引的":"可忽略
scores[[1,3]]

array([[60, 64, 80, 75, 80, 92, 90],
       [80, 82, 91, 88, 83, 86, 80]])

In [17]:
# 访问部分列元素，前面的行索引":"不可省略
scores[:, [0,1]]

array([[70, 85],
       [60, 64],
       [90, 93],
       [80, 82],
       [88, 72]])

In [18]:
# 访问部分行和列数据 eg.索引为0和3的行中，1~3列的所有元素
scores[[0,3], 1:4]

array([[85, 77, 90],
       [82, 91, 88]])

In [19]:
# 如需抽取某些行中指定列的所有元素，则需进行两层切片
scores[[1,3]][:,[0,1]]

array([[60, 64],
       [80, 82]])

In [20]:
# 条件筛选，行索引使用布尔数组给出
names = np.array(['王微', '肖良英', '方绮雯', '刘旭阳', '钱易铭'])
scores[(names == '肖良英')|(names == '方绮雯'), :]

array([[60, 64, 80, 75, 80, 92, 90],
       [90, 93, 88, 87, 86, 90, 91]])

In [21]:
# 两层筛选
subjects = np.array(['Math', 'English', 'Python', 'Chinese', 'Art', 'Database', 'Physics'])
scores[(names == '肖良英')|(names == '方绮雯'), :][:,(subjects == 'Math')|(subjects == 'Python')]

array([[60, 80],
       [90, 88]])

### 2.1.3 创建多维数组的常用方法

In [22]:
# arange()函数 给定范围和布长
print(np.arange(0, 11))
print(np.arange(3, 11, 2))
# arange函数的3个参数可为浮点数
print(np.arange(0.3, 1.5, 0.3))

[ 0  1  2  3  4  5  6  7  8  9 10]
[3 5 7 9]
[0.3 0.6 0.9 1.2]


In [23]:
# reshape()函数 将一维数组转换为指定的多维数组
# reshape(n, m) n表示行数,m表示列数
np.arange(0, 15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
# zeros()和ones()函数生成指定大小的全0和全1数组
# 参数为元组(n,m), n表示行数, m表示列数
print(np.zeros((3, 4)))
print(np.ones((4, 3)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
